### ISSUE TITLE
Les actions requises n'apparaissent pas dans "Marche à suivre" Natura 2000

### ISSUE THREAD

**Issue by nenj** [MTES-MCT/envergo#99]
Exemple : https://envergo.beta.gouv.fr/simulateur/resultat/?created_surface=1000&existing_surface=0&lng=-1.84542&lat=47.19523
Dans le cadre "Marche à suivre" de Natura 2000 on lit :

> Pour être certain que son projet n'est pas soumis à Natura 2000, le porteur doit s'assurer que celui-ci :

Suivi de rien du tout.

Il semble que les variables testées dans le template de résultat ne correspondent pas au nom des variables effectivement remontées par la moulinette :

https://github.com/MTES-MCT/envergo/blob/6d8166acb297aad6261032ee5bcf6a8d45b49a34/envergo/templates/moulinette/natura2000/result_action_requise.html#L10

**Comment by thibault** [comment]
Corrigé dans la pr #100
